steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/arbitragescan/helloworld-nodejs:$SHORT_SHA", "." ]
    # push container image
  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/arbitragescan/helloworld-nodejs:$SHORT_SHA" ]
    # deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - '-image=gcr.io/arbitragescan/helloworld-nodejs:$SHORT_SHA'
      - '-location=us-central1'
      - '-cluster=eigenphi-us-central-1'
      - '-filename=deployment.yaml'
  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'service.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=eigenphi-us-central-1'
substitutions:
  _COMMIT_SHA: $SHORT_SHA

options:
  env:
    - 'COMMIT_SHA=$COMMIT_SHA'