steps:
  - name: 'node:14'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install
        npm run build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/helloworld-nodejs:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/helloworld-nodejs:$COMMIT_SHA']
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=us-central1
      - --cluster=eigenphi-us-central-1

substitutions:
  _COMMIT_SHA: $SHORT_SHA

options:
  env:
    - 'COMMIT_SHA=$COMMIT_SHA'