apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nodejs
  namespace: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-nodejs
  template:
    metadata:
      labels:
        app: helloworld-nodejs
    spec:
      containers:
        - name: helloworld-nodejs
          image: gcr.io/arbitragescan/fake-app
          ports:
            - containerPort: 8080
          env:
            - name: ENV  # 设置环境变量名称
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_NAME  # 设置应用名
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /liveness_check
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 2
            successThreshold: 1
