apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nodejs
  namespace: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-nodejs
  template:
    metadata:
      labels:
        app: helloworld-nodejs
    spec:
      containers:
        - name: helloworld-nodejs
          image: gcr.io/arbitragescan/helloworld-nodejs
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /liveness_check
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness_check
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 2
            successThreshold: 1