apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-nodejs
  namespace: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-nodejs
  template:
    metadata:
      labels:
        app: helloworld-nodejs
    spec:
      containers:
        - name: helloworld-nodejs
          image: gcr.io/arbitragescan/fake-app
          ports:
            - containerPort: 8080
